### ISSUE TITLE
"Les Misérables" should be correctly spelt with an /eacute

### ISSUE THREAD

**Issue by drj11** [pnnl/HyperNetX#129]
**Describe the bug**

The title "Les Miserables" appears in Tutorial 1; it should be spelt with an eacute: Les Misérables

Possibly the bad orthography appears elsewhere too.

**Comment by bonicim** [comment]
Fixed in [v2.1.3](https://github.com/pnnl/HyperNetX/releases/tag/v2.1.3).

**Comment by bonicim** [comment]
Fixed in [v2.1.3](https://github.com/pnnl/HyperNetX/releases/tag/v2.1.3).

**Comment by szhorvat** [comment]
I'm certainly not going to nitpick on spelling :-) But if you _are_ going to put effort into fixing this, it should be done properly before closing this issue. While this was fixed in Tutorial 1, all the rest of the tutorials (which contain this title more times than Tutorial 1) still say "Les Miserables". It's also a good idea to pay attention to the rest of the docs, e.g. Erdős-Rényi instead of Erdos-Renyi.

**Comment by drj11** [comment]
His proxy Here On Earth (namely, my supervisor at the time), made sure i spelled Erdős correctly with the Hungarian accent when i was editing an article.
