### ISSUE TITLE
[joss] HyperNetX Widget not working

### ISSUE THREAD

**Issue by szhorvat** [pnnl/HyperNetX#143]
The HyperNetX Widget is prominently mentioned in both the documentation and the JOSS paper. https://hypernetx.readthedocs.io/en/latest/widget.html Unfortunately I wasn't able to get it working. Can you help with this?

The paper states that the widget works in Jupyter notebooks. After evaluating the first cell from [the demo notebook](https://github.com/pnnl/hypernetx-widget/blob/master/notebooks/example%20widget.ipynb), I see the following output only:

![image](https://github.com/pnnl/HyperNetX/assets/1212871/99dfe804-0cc2-4b56-9a00-324184cd9235)

No interactive widget appears.

I am using:

 - Jupyter Lab 4.0.8
 - HNX 2.1.3 and hnxwdget 0.1.1b3 (both from PyPI)
 - Python 3.11

The documentation goes into great detail on how to operate the graphical interface provided by the widget, but it is silent on how to make the widget appear and what code to run to create the widget (i.e. the prerequisites to enabling the described GUI). This should be remedied. https://hypernetx.readthedocs.io/en/latest/widget.html

Ref: https://github.com/openjournals/joss-reviews/issues/6016

**Comment by bonicim** [comment]
Taking a look.

**Comment by szhorvat** [comment]
It is entirely possible that something's wrong with my setup. Help with fixing this would be appreciated.

**Comment by bonicim** [comment]
I reproduced the issue using the same configuration. I have tried to use the widget on both Jupyter notebook and Jupyter lab. We are currently working on resolving this issue.

**Comment by bonicim** [comment]
@szhorvat After working with the team on this issue, it appears that `hnxwidget` will now only work on the Anaconda platform (i.e use a conda environment instead of a vanilla `venv` virtual environment). You are right that the documentation needs to be updated and I will start work on that. In the meanwhile, below are my notes on how to use the widget. Also attached is a screenshot of what to expect on Jupyter notebook.

----------Notes---------
# How to run HNX widget

`hnxwidget` is currently in beta and will only work on Jupyter Notebook 6.5.x. It is currently not yet supported on Jupyter Lab. Moreover, `hnxwidget` is currently supported only on the [Anaconda platform](https://www.anaconda.com/); therefore, it is highly recommended to use a `conda` environment to use this widget. Do not use python's builtin `venv` module or `virtualenv`. 

## Prerequisites

* conda 23.11.x
* python 3.11.x
* jupyter notebook 6.5.4
* ipywidgets 7.6.5

## Instructions
Open a new shell and run the following commands.

```
# update conda
conda update conda

# activate the base environment
conda activate

# install hypernetx and hnxwidget
pip install hypernetx hnxwidget

# install jupyter notebook and extensions
conda install -y -c anaconda notebook
conda install -y -c conda-forge jupyter_contrib_nbextensions

# install and enable the hnxwidget on jupyter
jupyter nbextension install --py --symlink --sys-prefix hnxwidget
jupyter nbextension enable --py --sys-prefix hnxwidget

# install ipykernel and use it to add the base environment to jupyter notebook
conda install -y -c anaconda ipykernel
python -m ipykernel install --user --name=base

# start the notebook
jupyter-notebook
```

Refs:
[How to add your Conda environment to your jupyter notebook in just 4 steps \| by Noopur R K | Medium](https://medium.com/@nrk25693/how-to-add-your-conda-environment-to-your-jupyter-notebook-in-just-4-steps-abeab8b8d084)
 

![Screenshot 2024-01-23 at 15 11 28](https://github.com/pnnl/HyperNetX/assets/6901848/b23c7b9b-5b95-481e-a8a1-7cd9278f83bd)

**Comment by bonicim** [comment]
The HyperNetX widget is currently in beta with limitations on the Jupyter environment in which it may be used.  It is being actively worked on. Look for improvements and an expanded list of usable environments in a future release. 

In addition, updates to the documentation are currently in progress and are planned to be published in the next week or so.

**Comment by bonicim** [comment]
Resolved in release 2.14

**Comment by szhorvat** [comment]
Can you please clarify what you mean here?

> It is highly recommended to use the base environment provided by Anaconda because Anaconda’s package management system, conda, will resolve dependencies when HyperNetX and HyperNetXWidget are installed.

Is it suggesting to install HNX and HNXWidget in the base environment instead of a dedicated environment? If so, why? My impression was that installing everything in the base environment was not considered good practice.

**Comment by szhorvat** [comment]
Can you please clarify this?

**Comment by drj11** [comment]
I agree that installing everything in the base environment is not best practice, but it's still a very widely established practice. As long it's documented, i personally would not withhold a publication recommendation on that basis.

**Comment by bonicim** [comment]
Have updated the environment setup steps for the widget: https://hypernetx.readthedocs.io/en/latest/widget.html#installation
